### ISSUE TITLE
应该如何运行此工程？

### ISSUE THREAD

**Issue by FLYING37520** [Tugraph/CD-SGD#4]
抱歉，我对MXnet完全不熟悉，请问我应该从哪里开始了解此项目？

**Comment by Tugraph** [comment]
我的论文题目是CD-SGD: Distributed Stochastic Gradient Descent with Compression and Delay Compensation，这是会议版本的，后面我发现会议版本的代码存在由热身向正式训练会有短暂精度波动问题（由ICPP21 reviewer提出），于是我们在JPDC的CP-SGD: Distributed Stochastic Gradient Descent with Compression and Periodic Compensation中对此进行修正。实际上该项目的思路比较易于理解：周期性地将非压缩通信插入压缩通信之间以打破残差累积+用本地权重代替全局权重快速启动下次迭代训练。 至于代码复现 你可以再download以后重新在Makefile目录下重新编译之后在example目录下运行测试脚本。当然我认为该项目在pytorch等框架同样是易于复现且效果显著的

**Comment by FLYING37520** [comment]
感谢回复！ 先前拜读过这篇论文，是一篇有启发性的文章，大概能看明白了，谢谢！
